films/urls.py
from django.urls import path
from . import views


app_name = "films"

urlpatterns = [
        path("", views.IndexView.as_view(), name="index"),
        # ex: film/314/
        path("film/<pk>/", views.DetailView.as_view(), name="detail"),
        # ex: search/?q=django+unchained
        path("search/", views.SearchView.as_view(), name="search"),
        # ex: film/314/delete
        path("film/<pk>/delete/", views.FilmDelete.as_view(), name="delete"),
        # ex: to_watch/
        path("to_watch/", views.ToWatchView.as_view(), name="to_watch"),
        # ex: completed/
        path("completed/", views.CompletedView.as_view(), name="completed"),
        # ex: film/314/mark_as_completed/
        path("film/<pk>/mark_as_completed/", views.MarkAsCompleted.as_view(), name="mark_as_completed"),
]

watchlist/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
        path('admin/', admin.site.urls),
        path("", include("films.urls"))
]

films/models.py
from django.db import models
from django.urls import reverse

from model_utils import Choices


class Film(models.Model):
    STATUSES = Choices(("to_watch", "хочу посмотреть"), ("completed", "просмотренное"))

    kinopoisk_id = models.CharField(max_length=10)
    title = models.CharField(max_length=100)
    title_original = models.CharField(max_length=100)
    year = models.PositiveSmallIntegerField()
    country = models.CharField(max_length=50)
    poster = models.URLField()
    genre = models.CharField(max_length=50)
    director = models.CharField(max_length=200)
    scriptwriter = models.CharField(max_length=200)
    actors = models.CharField(max_length=200)
    plot = models.TextField(max_length=1000)
    length = models.PositiveSmallIntegerField()
    status = models.CharField(choices=STATUSES, default=STATUSES.to_watch, max_length=9)
    edit_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title + " (" + str(self.year) + ")"

    def get_absolute_url(self):
        return reverse("films:detail", kwargs={"pk": self.pk})

films/views.py
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import DeleteView
from django.shortcuts import render
from django.urls import reverse_lazy

from kinopoisk.movie import Movie

from films.models import Film


class IndexView(ListView):
    template_name = "films/index.html"
    context_object_name = "all_films"

    def get_queryset(self):
        return Film.objects.all()

    def get(self, request):
        to_watch_films = Film.objects.filter(status="to_watch").order_by("-edit_time")[:4]
        completed_films = Film.objects.filter(status="completed").order_by("-edit_time")[:4]
        return render(request, self.template_name, {"to_watch_films": to_watch_films,
                                                    "completed_films": completed_films})

    def post(self, request):
        self.helper(request)
        to_watch_films = Film.objects.filter(status="to_watch").order_by("-edit_time")
        completed_films = Film.objects.filter(status="completed").order_by("-edit_time")
        return render(request, self.template_name, {"to_watch_films": to_watch_films,
                                                    "completed_films": completed_films})

    def helper(self, request):
        # pulls all required info from kinopoisk
        kinopoisk_id = request.POST.get("kinopoisk_id")
        kinopoisk_info = Movie(id=kinopoisk_id)
        kinopoisk_info.get_content("main_page")
        film = Film()
        film.kinopoisk_id = kinopoisk_id
        film.title = kinopoisk_info.title
        film.title_original = kinopoisk_info.title_original
        film.year = kinopoisk_info.year
        film.country = ", ".join(kinopoisk_info.countries)
        film.poster = "https://st.kp.yandex.net/images/film_iphone/iphone360_" + kinopoisk_id + ".jpg"
        film.genre = ", ".join(kinopoisk_info.genres)
        film.director = ", ".join(kinopoisk_info.directors)
        film.scriptwriter = ", ".join(kinopoisk_info.screenwriters)
        film.actors = ", ".join(kinopoisk_info.actors)
        film.plot = kinopoisk_info.plot
        film.length = kinopoisk_info.runtime
        film.status = self.status
        film.save()


class ToWatchView(IndexView):
    template_name = "films/to_watch.html"
    context_object_name = "to_watch_films"
    films = Film.objects.filter(status="to_watch").order_by("-edit_time")
    status = "to_watch" # is used in the helper function

    def get(self, request):
        return render(request, self.template_name, {"to_watch_films": self.films})

    def post(self, request):
        self.helper(request)
        return render(request, self.template_name, {"to_watch_films": self.films})


class CompletedView(IndexView):
    template_name = "films/completed.html"
    context_object_name = "completed_films"
    films = Film.objects.filter(status="completed").order_by("-edit_time")
    status = "completed" # is used in the helper function

    def get(self, request):
        return render(request, self.template_name, {"completed_films": self.films})

    def post(self, request):
        self.helper(request)
        return render(request, self.template_name, {"completed_films": self.films})


class DetailView(DetailView):
    model = Film
    template_name = "films/detail.html"


class MarkAsCompleted(TemplateView):
    template_name = "films/completed.html"

    def post(self, request, pk):
        queryset = Film.objects.filter(pk=pk)
        for film in queryset:
            film.status = "completed"
            film.save()
        return render(request, self.template_name, {"completed_films": Film.objects.filter(status="completed")})


class FilmDelete(DeleteView):
    model = Film
    success_url = reverse_lazy("films:index")


class SearchView(TemplateView):
    template_name = "films/search.html"

    def get(self, request):
        query = request.GET.get("q", None)
        search_result = Movie.objects.search(query)
        ids = []
        titles = []
        years = []
        posters = []
        for film in search_result:
            ids.append(str(film.id))
            titles.append(film.title)
            years.append(film.year)
            posters.append("https://st.kp.yandex.net/images/film_iphone/iphone360_"
                           + str(film.id) + ".jpg")
        # replacing Nones with TBAs in movies with no release date.
        years = ["TBA" if x is None else x for x in years]
        base_info = list(zip(ids, titles, years, posters))
        # sorting movies by release year (desc),
        # movies with no release date are moved to the top.
        base_info.sort(key=lambda x: (type(x[2]) is not int, x[2]), reverse=True)
        return render(request, self.template_name, {"base_info": base_info,
                            "results": len(search_result), "q": query})

films/templates/films/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <!-- Static CSS -->
    <link rel="stylesheet" href="{% static 'films/style.css' %}">

    <title>{% block title %}Вочлист{% endblock %}</title>
</head>

<body>



<div class="container">

    <nav class="navbar navbar-expand-lg navbar-light bg-warning" >
      <a class="navbar-brand" href="{% url 'films:index' %}">Вочлист</a>
        <div class="navbar-collapse">
          <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'films:to_watch' %}">Хочу посмотреть</a>
            <a class="nav-item nav-link" href="{% url 'films:completed' %}">Просмотренное</a>
          </div>
        </div>
        <form class="form-inline" action="{% url 'films:search' %}" method="get">
          <input class="form-control mr-sm-2" type="search" name="q" placeholder="Введите название фильма" value="{{ q }}">
          <button class="btn btn-light" type="submit">Поиск</button>
        </form>
    </nav>

    {% block body %}
    {% endblock %}
</div>

</body>

</html>

films/templates/films/completed.html
{% extends "films/base.html" %}

{% block body %}
<div class="block-wrap">
  <div class="block-header">
    <h1>Просмотренное</h1>
  </div>
  <div class="block">
  {% if completed_films %}
    <div class="card-deck">
    {% for film in completed_films %}
      <div class="col-md-3 col-xs-6">
        <div class="card">
          <a href="{% url 'films:detail' film.id %}">
            <img class="card-img-top" src="{{ film.poster }}" alt="{{ film.title }}">
          </a>
          <div class="card-block">
            <h2 class="card-title">{{ film.title }} ({{ film.year }})</h2>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
    {% else %}
      <p><em>Вы пока не добавили ни одного фильма.</em></p>
  {% endif %}
  </div>
</div>
{% endblock %}

films/templates/films/detail.html
{% extends "films/base.html" %}
{% load staticfiles %}

{% block title %}{{ film }} &mdash; Вочлист{% endblock %}


{% block body %}

<div class="block-wrap">
  <div class="block-header">
    <h1>{{ film.title }}</h1>
    <p>{{ film.title_original }}</p>
  </div>

  <div class="actions-block">
    <!-- изменить статус на просмотренное -->
    <div class="action">
      {% if film.status == "to_watch" %}
      <form action="{% url 'films:mark_as_completed' film.id %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="film_id" value="{{ film.id }}">
          <input class="action-icon" type="image" src="{% static 'films/images/task.svg' %}" title="Отметить как просмотренное"></input>
      </form>
      {% endif %}
    </div>

    <!-- удалить -->
    <div class="action">
    <form action="{% url 'films:delete' film.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="film_id" value="{{ film.id }}">
        <input class="action-icon" type="image" src="{% static 'films/images/trash.svg' %}" title="Удалить"</input>
    </form>
    </div>
  </div>

  <div class="block">
    <div style="display: flex; justify-content: space-between;">
      <div class="block-poster">
        <img src="{{ film.poster }}">
      </div>
      <div class="block-plot">
          {{ film.plot }}
      </div>
    </div>
  </div>

  <div class="block">
    <div>
      <table>
        <tr>
          <th>
            Год:
          </th>
          <td>
            {{ film.year }}
          </td>
        </tr>
        <tr>
          <th>
            Страна:
          </th>
          <td>
            {{ film.country }}
          </td>
        </tr>
        <tr>
          <th>
            Жанр:
          </th>
          <td>
            {{ film.genre }}
          </td>
        </tr>
        <tr>
          <th>
            В главных ролях:
          </th>
          <td>
            {{ film.actors }}
          </td>
        </tr>
        <tr>
          <th>
            Режиссер:
          </th>
          <td>
            {{ film.director }}
          </td>
        </tr>
        <tr>
          <th>
            Сценарий:
          </th>
          <td>
            {{ film.scriptwriter }}
          </td>
        </tr>
        <tr>
          <th>
            Продолжительность:
          </th>
          <td>
            {{ film.length }} минут
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

{% endblock %}

films/templates/films/index.html
{% extends "films/base.html" %}

{% block body %}

<!-- начало блока "хочу посмотреть" -->
<div class="block-wrap">
  <div class="block-header">
    <h1>Хочу посмотреть</h1>
  </div>
  <div class="block">
  {% if to_watch_films %}
    <div class="card-deck">
    {% for film in to_watch_films %}
      <div class="col-md-3 col-xs-6">
        <div class="card">
          <a href="{% url 'films:detail' film.id %}">
            <img class="card-img-top" src="{{ film.poster }}" alt="{{ film.title }}">
          </a>
          <div class="card-block">
            <h3 class="card-title">{{ film.title }} ({{ film.year }})</h3>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
    {% else %}
      <p><em>Вы пока не добавили ни одного фильма.</em></p>
  {% endif %}
  </div>
</div>
<!-- конец блока "хочу посмотреть" -->

<!-- начало блока "просмотренное" -->
<div class="block-wrap">
  <div class="block-header">
    <h1>Просмотренное</h1>
  </div>
  <div class="block">
  {% if completed_films %}
    <div class="card-deck">
    {% for film in completed_films %}
      <div class="col-md-3 col-xs-6">
        <div class="card">
          <a href="{% url 'films:detail' film.id %}">
            <img class="card-img-top" src="{{ film.poster }}" alt="{{ film.title }}">
          </a>
          <div class="card-block">
            <h3 class="card-title">{{ film.title }} ({{ film.year }})</h3>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
    {% else %}
      <p><em>Вы пока не добавили ни одного фильма.</em></p>
  {% endif %}
  </div>
</div>
<!-- конец блока "просмотренное" -->

{% endblock %}

films/templates/films/search.html
{% extends "films/base.html" %}
{% load staticfiles %}

{% block body %}

<div class="block-wrap">
  <div class="block-header">
    <h1>Результаты поиска для <em>{{ q }}</em> ({{ results }})</h1>
  </div>

{% if results == 0 %}
<div class="block">
  <p>К сожалению, по вашему запросу ничего не найдено...<p>
  <h2>Что делать?</h2>
</div>

{% else %}
  <div class="block">
    <div class="card-deck">
    {% for uid, title, year, poster in base_info %}
      <!-- film card -->
      <div class="col-md-3 col-xs-6">
        <div class="card">
            <!-- <a href="https://www.kinopoisk.ru/film/{{ uid }}"> -->
              <img class="card-img-top" src="{{ poster }}" alt="{{ title }}">
            <!-- </a> -->
          <div class="card-block"
            <h2 class="card-title">{{ title }} ({{ year }})</h2>
          </div>
          <div class="actions-block">
            <!-- add to the to_watch list -->
            <div>
              <form action="{% url 'films:to_watch' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="kinopoisk_id" value="{{ uid }}">
                <input class="action-icon icon-left" type="image" src="{% static 'films/images/eye-overlay.png' %}" title="Хочу посмотреть"></input>
              </form>
            </div>
            <!-- add to the completed list -->
            <div>
              <form action="{% url 'films:completed' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="kinopoisk_id" value="{{ uid }}">
                <input class="action-icon icon-right text-warning" type="image" src="{% static 'films/images/task-overlay.png' %}" title="Добавить в просмотренное"></input>
              </form>
            </div>
          </div>
        </div>
      </div>
          <!-- end of a film card -->
    {% endfor %}
    </div>
  </div>
</div>

<div class="block-wrap">
  <div class="block-header">
    <h2>Не нашли что искали?</h2>
  </div>

{% endif %}
  <div class="block">
    <ul>
      <li>Попробуйте изменить запрос. Многие фильмы имеют несколько названий.</li>
      <li>Используйте вариант названия фильма на английском языке.</li>
    </ul>
  </div>
</div>
{% endblock %}

films/templates/films/to_watch.html
{% extends "films/base.html" %}


{% block body %}
<div class="block-wrap">
  <div class="block-header">
    <h1>Хочу посмотреть</h1>
  </div>
  <div class="block">
  {% if to_watch_films %}
    <div class="card-deck">
    {% for film in to_watch_films %}
      <div class="col-md-3 col-xs-6">
        <div class="card">
          <a href="{% url 'films:detail' film.id %}">
            <img class="card-img-top" src="{{ film.poster }}" alt="{{ film.title }}">
          </a>
          <div class="card-block">
            <h2 class="card-title">{{ film.title }} ({{ film.year }})</h2>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
    {% else %}
      <p><em>Вы пока не добавили ни одного фильма.</em></p>
  {% endif %}
  </div>
</div>
{% endblock %}